package com.compi2.simpascal.interfaz;

import java.awt.Color;

/**
 *
 * @author mgome
 */
public class MFrame extends javax.swing.JFrame {

    /**
     * Creates new form MFrame
     */
    public MFrame() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.compi2.simpascal.interfaz.PanelBorder();
        titleBar1 = new com.compi2.simpascal.interfaz.TitleBar();
        card = new javax.swing.JPanel();
        editor = new javax.swing.JPanel();
        tituloConsola = new javax.swing.JLabel();
        tabPanel2 = new com.compi2.simpascal.interfaz.TabPanel();
        consolePanel2 = new com.compi2.simpascal.interfaz.ConsolePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(50, 50, 50));
        panelBorder1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 32, 30), 5, true));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBorder1.add(titleBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        card.setLayout(new java.awt.CardLayout());

        editor.setBackground(new java.awt.Color(50, 50, 50));
        editor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloConsola.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        tituloConsola.setForeground(new java.awt.Color(18, 175, 177));
        tituloConsola.setText("Consola");
        editor.add(tituloConsola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));
        editor.add(tabPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));
        editor.add(consolePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1000, 130));

        card.add(editor, "card2");

        panelBorder1.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1020, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card;
    private com.compi2.simpascal.interfaz.ConsolePanel consolePanel2;
    private javax.swing.JPanel editor;
    private com.compi2.simpascal.interfaz.PanelBorder panelBorder1;
    private com.compi2.simpascal.interfaz.TabPanel tabPanel2;
    private com.compi2.simpascal.interfaz.TitleBar titleBar1;
    private javax.swing.JLabel tituloConsola;
    // End of variables declaration//GEN-END:variables
}
