package com.compi2.simpascal.interfaz;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;

/**
 *
 * @author mgome
 */
public class TablaErrores extends javax.swing.JPanel {

    /**
     * Creates new form TablaSimbolos
     */
    public TablaErrores() {
        initComponents();
        tablaS.setDefaultRenderer(Object.class, new GradienteTabla(Color.decode("#E36679"), Color.decode("#D642A6")));
        this.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:1,1,1,1,$TableHeader.bottomSeparatorColor,,10");
        tablaS.getTableHeader().putClientProperty(FlatClientProperties.STYLE, ""
                + "hoverBackground:null;"
                + "pressedBackground:null;"
                + "separatorColor:$TableHeader.background");
        jScrollPane1.putClientProperty(FlatClientProperties.STYLE, ""
                + "border:3,0,3,0,$Table.background,10,10");
        jScrollPane1.getVerticalScrollBar().putClientProperty(FlatClientProperties.STYLE, ""
                + "hoverTrackColor:null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaS = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        tituloArchivo = new javax.swing.JLabel();

        setOpaque(false);

        tablaS.setBackground(new java.awt.Color(51, 51, 51));
        tablaS.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tablaS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Tipo", "Descripcion", "Linea", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaS.setRowHeight(25);
        tablaS.setSelectionBackground(new java.awt.Color(227, 102, 121));
        tablaS.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tablaS);
        if (tablaS.getColumnModel().getColumnCount() > 0) {
            tablaS.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablaS.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablaS.getColumnModel().getColumn(2).setPreferredWidth(400);
            tablaS.getColumnModel().getColumn(3).setPreferredWidth(20);
            tablaS.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        titulo.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(227, 102, 121));
        titulo.setText("Tabla de Errores:");

        tituloArchivo.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        tituloArchivo.setForeground(new java.awt.Color(227, 102, 121));
        tituloArchivo.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tituloArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(tituloArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaS;
    private javax.swing.JLabel titulo;
    public javax.swing.JLabel tituloArchivo;
    // End of variables declaration//GEN-END:variables
}
